In [1]:
import numpy as np

In [2]:
M = np.linspace(0,199,200).reshape(10,20)

In [3]:
M

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.],
       [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119.],
       [120., 121., 122., 123., 124., 125., 126., 127., 128., 129., 130.,
        131., 132., 133., 134., 135., 136., 137., 138., 139.],
       [140., 141., 142., 143., 144., 145

In [4]:
M.shape

(10, 20)

In [5]:
M[2:5,5:8]

array([[45., 46., 47.],
       [65., 66., 67.],
       [85., 86., 87.]])

In [6]:
np.zeros(20).reshape(20,1).shape

(20, 1)

In [7]:
b = np.zeros(20).reshape(-1,1)
b[2] = 1

In [8]:
b

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
M.dot(b)

array([[  2.],
       [ 22.],
       [ 42.],
       [ 62.],
       [ 82.],
       [102.],
       [122.],
       [142.],
       [162.],
       [182.]])

In [10]:
np.array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.],
       [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119.],
       [120., 121., 122., 123., 124., 125., 126., 127., 128., 129., 130.,
        131., 132., 133., 134., 135., 136., 137., 138., 139.],
       [140., 141., 142., 143., 144., 145., 146., 147., 148., 149., 150.,
        151., 152., 153., 154., 155., 156., 157., 158., 159.],
       [160., 161., 162., 163., 164., 165., 166., 167., 168., 169., 170.,
        171., 172., 173., 174., 175., 176., 177., 178., 179.],
       [180., 181., 182., 183., 184., 185., 186., 187., 188., 189., 190.,
        191., 192., 193., 194., 195., 196., 197., 198., 199.]])

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.],
       [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119.],
       [120., 121., 122., 123., 124., 125., 126., 127., 128., 129., 130.,
        131., 132., 133., 134., 135., 136., 137., 138., 139.],
       [140., 141., 142., 143., 144., 145

In [11]:
from numpy import array

In [12]:
M

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.],
       [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119.],
       [120., 121., 122., 123., 124., 125., 126., 127., 128., 129., 130.,
        131., 132., 133., 134., 135., 136., 137., 138., 139.],
       [140., 141., 142., 143., 144., 145

In [13]:
M_example = array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.],
       [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119.],
       [120., 121., 122., 123., 124., 125., 126., 127., 128., 129., 130.,
        131., 132., 133., 134., 135., 136., 137., 138., 139.],
       [140., 141., 142., 143., 144., 145., 146., 147., 148., 149., 150.,
        151., 152., 153., 154., 155., 156., 157., 158., 159.],
       [160., 161., 162., 163., 164., 165., 166., 167., 168., 169., 170.,
        171., 172., 173., 174., 175., 176., 177., 178., 179.],
       [180., 181., 182., 183., 184., 185., 186., 187., 188., 189., 190.,
        191., 192., 193., 194., 195., 196., 197., 198., 199.]])

In [14]:
print(M.__repr__())

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.],
       [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119.],
       [120., 121., 122., 123., 124., 125., 126., 127., 128., 129., 130.,
        131., 132., 133., 134., 135., 136., 137., 138., 139.],
       [140., 141., 142., 143., 144., 145

In [15]:
M.dot(b)

array([[  2.],
       [ 22.],
       [ 42.],
       [ 62.],
       [ 82.],
       [102.],
       [122.],
       [142.],
       [162.],
       [182.]])

In [16]:
list(M.dot(b))

[array([2.]),
 array([22.]),
 array([42.]),
 array([62.]),
 array([82.]),
 array([102.]),
 array([122.]),
 array([142.]),
 array([162.]),
 array([182.])]

In [17]:
print(M.dot(b))

[[  2.]
 [ 22.]
 [ 42.]
 [ 62.]
 [ 82.]
 [102.]
 [122.]
 [142.]
 [162.]
 [182.]]


In [18]:
M[1:3,:2]

array([[20., 21.],
       [40., 41.]])

In [19]:
M

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.],
       [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119.],
       [120., 121., 122., 123., 124., 125., 126., 127., 128., 129., 130.,
        131., 132., 133., 134., 135., 136., 137., 138., 139.],
       [140., 141., 142., 143., 144., 145

In [20]:
new_M_0 = np.concatenate((M,M))

In [21]:
new_M_0.shape

(20, 20)

In [22]:
new_M_1 = np.concatenate((M,M), axis=1)

In [23]:
new_M_1.shape

(10, 40)

In [24]:
M.T

array([[  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180.],
       [  1.,  21.,  41.,  61.,  81., 101., 121., 141., 161., 181.],
       [  2.,  22.,  42.,  62.,  82., 102., 122., 142., 162., 182.],
       [  3.,  23.,  43.,  63.,  83., 103., 123., 143., 163., 183.],
       [  4.,  24.,  44.,  64.,  84., 104., 124., 144., 164., 184.],
       [  5.,  25.,  45.,  65.,  85., 105., 125., 145., 165., 185.],
       [  6.,  26.,  46.,  66.,  86., 106., 126., 146., 166., 186.],
       [  7.,  27.,  47.,  67.,  87., 107., 127., 147., 167., 187.],
       [  8.,  28.,  48.,  68.,  88., 108., 128., 148., 168., 188.],
       [  9.,  29.,  49.,  69.,  89., 109., 129., 149., 169., 189.],
       [ 10.,  30.,  50.,  70.,  90., 110., 130., 150., 170., 190.],
       [ 11.,  31.,  51.,  71.,  91., 111., 131., 151., 171., 191.],
       [ 12.,  32.,  52.,  72.,  92., 112., 132., 152., 172., 192.],
       [ 13.,  33.,  53.,  73.,  93., 113., 133., 153., 173., 193.],
       [ 14.,  34.,  54.,  74.,  9

In [25]:
M.T.shape

(20, 10)

In [26]:
M[0]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [27]:
M[0,:]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [28]:
M[:,0]

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180.])

In [29]:
M[:,0].shape

(10,)

In [30]:
new_M = M[:,0]
for i in range(1,10):
    print('-'*40)
    print(new_M.shape)
    print(new_M)
    new_M = np.concatenate((new_M, M[:,i]))

print('-'*40)
print(new_M.shape)
print(new_M)

----------------------------------------
(10,)
[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.]
----------------------------------------
(20,)
[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.   1.  21.  41.  61.
  81. 101. 121. 141. 161. 181.]
----------------------------------------
(30,)
[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.   1.  21.  41.  61.
  81. 101. 121. 141. 161. 181.   2.  22.  42.  62.  82. 102. 122. 142.
 162. 182.]
----------------------------------------
(40,)
[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.   1.  21.  41.  61.
  81. 101. 121. 141. 161. 181.   2.  22.  42.  62.  82. 102. 122. 142.
 162. 182.   3.  23.  43.  63.  83. 103. 123. 143. 163. 183.]
----------------------------------------
(50,)
[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.   1.  21.  41.  61.
  81. 101. 121. 141. 161. 181.   2.  22.  42.  62.  82. 102. 122. 142.
 162. 182.   3.  23.  43.  63.  83. 103. 123. 143. 163. 183.   4.  24.
  44.  64.  84. 104. 124. 144. 164. 184

In [31]:
M[:,0]

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180.])

In [32]:
M[:,0]

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180.])

In [33]:
M[:,0].shape

(10,)

In [34]:
len(M[:,0])

10

In [35]:
new_M = M[:,0].reshape(-1,1)
for i in range(1,10):
    print('-'*40)
    print(new_M.shape)
    print(new_M)
    new_M = np.concatenate((new_M, M[:,i].reshape(-1,1)), axis=1)

print('-'*40)
print(new_M.shape)
print(new_M)

----------------------------------------
(10, 1)
[[  0.]
 [ 20.]
 [ 40.]
 [ 60.]
 [ 80.]
 [100.]
 [120.]
 [140.]
 [160.]
 [180.]]
----------------------------------------
(10, 2)
[[  0.   1.]
 [ 20.  21.]
 [ 40.  41.]
 [ 60.  61.]
 [ 80.  81.]
 [100. 101.]
 [120. 121.]
 [140. 141.]
 [160. 161.]
 [180. 181.]]
----------------------------------------
(10, 3)
[[  0.   1.   2.]
 [ 20.  21.  22.]
 [ 40.  41.  42.]
 [ 60.  61.  62.]
 [ 80.  81.  82.]
 [100. 101. 102.]
 [120. 121. 122.]
 [140. 141. 142.]
 [160. 161. 162.]
 [180. 181. 182.]]
----------------------------------------
(10, 4)
[[  0.   1.   2.   3.]
 [ 20.  21.  22.  23.]
 [ 40.  41.  42.  43.]
 [ 60.  61.  62.  63.]
 [ 80.  81.  82.  83.]
 [100. 101. 102. 103.]
 [120. 121. 122. 123.]
 [140. 141. 142. 143.]
 [160. 161. 162. 163.]
 [180. 181. 182. 183.]]
----------------------------------------
(10, 5)
[[  0.   1.   2.   3.   4.]
 [ 20.  21.  22.  23.  24.]
 [ 40.  41.  42.  43.  44.]
 [ 60.  61.  62.  63.  64.]
 [ 80.  81.  82.  8

In [36]:
np.block([[M,M],[M,M]])

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,   0.,   1.,
          2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  40.,  41.,
         42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,
         53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  60.,  61.,
         62.,  63.,  64.,  65.,  

In [37]:
np.block([[M,M],[M,M]]).shape

(20, 40)

In [38]:
l = [[1,2,3],[4,5,6],[7,8,9]]

In [39]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [40]:
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [41]:
np.array(l[:2])

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.array(l[:2]).shape

(2, 3)

In [43]:
np.array(l[:2]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
np.array(l[:2]).T

array([[1, 4],
       [2, 5],
       [3, 6]])